name: deploy-container

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup environment
        uses: actions/checkout@v2
        run: |
          echo "Upgrading pip"
          python -m pip install --upgrade pip
          echo "Installing Requirements"
          python -m pip install -r requirements.txt
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Copy files to the s3 website content bucket
        run: |
          mkdocs build
          aws s3 sync ./site s3://${{ secrets.AWS_S3_BUCKET_NAME }}
